new_logi/new_logi/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("zaiko.urls")),
    path('zaiko2/',include("zaiko2.urls")),
]

new_logi/zaiko/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import index,check_0,hinban_enter,hinban_click,color_size_click,place_click,item_add,item_del,order_item_list,order_csv_check,csv_item_add, \
                    zaiko_last_check,ajax_regular_day,irai_send_all,rireki_index,rireki_search,rireki_detail,irai_change_today,irai_cancel, \
                    page_first,page_prev,page_next,page_last,download_excel_1, \
                    irai_reset,irai_keep_hassou,csv_imp,csv_imp_page,free


app_name="zaiko"
urlpatterns = [
    path('', index, name="index"),
    path('login/', auth_views.LoginView.as_view(template_name='zaiko/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('check_0/', check_0, name="check_0"),
    path('hinban_enter/', hinban_enter, name="hinban_enter"),
    path('hinban_click/', hinban_click, name="hinban_click"),
    path('color_size_click/', color_size_click, name="color_size_click"),
    path('place_click/', place_click, name="place_click"),
    path('item_add/', item_add, name="item_add"),
    path('item_del/', item_del, name="item_del"),
    path('order_item_list/', order_item_list, name="order_item_list"),
    path('order_csv_check/', order_csv_check, name="order_csv_check"),
    path('csv_item_add/', csv_item_add, name="csv_item_add"),
    path('zaiko_last_check/', zaiko_last_check, name="zaiko_last_check"),
    path('ajax_regular_day/', ajax_regular_day, name="ajax_regular_day"),
    path('irai_send_all/', irai_send_all, name="irai_send_all"),
    path('rireki_index/', rireki_index, name="rireki_index"),
    path('rireki_search/', rireki_search, name="rireki_search"),
    path('rireki_detail/<int:pk>', rireki_detail, name="rireki_detail"),
    path('irai_change_today/', irai_change_today, name="irai_change_today"),
    path('irai_cancel/', irai_cancel, name="irai_cancel"),
    path('irai_reset/', irai_reset, name="irai_reset"),
    path('irai_keep_hassou/', irai_keep_hassou, name="irai_keep_hassou"),
    path('page_first/', page_first, name="page_first"),
    path('page_prev/', page_prev, name="page_prev"),
    path('page_next/', page_next, name="page_next"),
    path('page_last/', page_last, name="page_last"),

    path('download_excel_1/', download_excel_1, name="download_excel_1"),
    path('csv_imp/', csv_imp, name="csv_imp"),
    path('csv_imp_page/', csv_imp_page, name="csv_imp_page"),
    path('free/', free, name="free"),
]

new_logi/zaiko2/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import henshu_index,henshu_hinban_enter,henshu_hinban_click,henshu_color_size_click,henshu_list_click,henshu_up,henshu_del,henshu_excel_download, \
                    size_index,size_num_func,size_new,size_name,size_del,size_same,nyuuko_index,excel_download,excel_import,nyuuko_send, \
                    vba_irai_list,vba_hassou_data,vba_zaiko_list


app_name="zaiko2"
urlpatterns = [
    path('henshu_index', henshu_index, name="henshu_index"),
    path('henshu_hinban_enter', henshu_hinban_enter, name="henshu_hinban_enter"),
    path('henshu_hinban_click', henshu_hinban_click, name="henshu_hinban_click"),
    path('henshu_color_size_click', henshu_color_size_click, name="henshu_color_size_click"),
    path('henshu_list_click', henshu_list_click, name="henshu_list_click"),
    path('henshu_up', henshu_up, name="henshu_up"),
    path('henshu_del', henshu_del, name="henshu_del"),
    path('henshu_excel_download', henshu_excel_download, name="henshu_excel_download"),
    path('size_index', size_index, name="size_index"),
    path('size_num_func', size_num_func, name="size_num_func"),
    path('size_new', size_new, name="size_new"),
    path('size_name', size_name, name="size_name"),
    path('size_del', size_del, name="size_del"),
    path('size_same', size_same, name="size_same"),
    path('nyuuko_index', nyuuko_index, name="nyuuko_index"),
    path('excel_download', excel_download, name="excel_download"),
    path('excel_import', excel_import, name="excel_import"),
    path('nyuuko_send', nyuuko_send, name="nyuuko_send"),
    path('vba_irai_list', vba_irai_list, name="vba_irai_list"),
    path('vba_hassou_data', vba_hassou_data, name="vba_hassou_data"),
    path('vba_zaiko_list', vba_zaiko_list, name="vba_zaiko_list"),
]

new_logi/zaiko2/models.py
from django.db import models

# Create your models here.

new_logi/zaiko2/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from zaiko.models import Shouhin,Size,Place,Irai_list,Irai_detail
import datetime
from django.http import JsonResponse
import io
import csv
import json
from django.db.models import Max
from zaiko.views import order_item_list
import pandas as pd
from io import BytesIO
from django.http import HttpResponse
from django_pandas.io import read_frame
import openpyxl
from django.views.decorators.csrf import csrf_exempt


# 編集画面
@login_required
def henshu_index(request):
    place_list=Place.objects.all()
    size_list=Size.objects.all()
    request.session["zaiko"]["now_page"]="編集"
    params={
        "size_list":size_list,
        "place_list":place_list,
    }
    return render(request,"zaiko2/henshu.html",params)


# 編集_品番検索に入力
def henshu_hinban_enter(request):
    hinban=request.POST.get("hinban_enter")
    hinban_list=list(Shouhin.objects.filter(shouhin_set__icontains=hinban).values_list("shouhin_set",flat=True).order_by("shouhin_set").distinct())
    d={"hinban_list":hinban_list}
    return JsonResponse(d)


# 編集_品番クリック
def henshu_hinban_click(request):
    hinban=request.POST.get("hinban")
    item_list=list(Shouhin.objects.filter(shouhin_set=hinban).order_by("color","size_num").values())
    color_list=list(Shouhin.objects.filter(shouhin_set=hinban).values_list("color",flat=True).order_by("color").distinct())
    size_list=list(Shouhin.objects.filter(shouhin_set=hinban).values_list("size",flat=True).order_by("size_num").distinct())
    d={
        "item_list":item_list,
        "color_list":color_list,
        "size_list":size_list,
        }
    return JsonResponse(d)


# 編集_モーダル_カラー、サイズをクリック
def henshu_color_size_click(request):
    hinban=request.POST.get("hinban")
    color=request.POST.get("color")
    color=json.loads(color)
    size=request.POST.get("size")
    size=json.loads(size)
    d={
        "item_list":item_list(hinban,color,size),
        }
    return JsonResponse(d)


# FUNC 商品リスト取得
def item_list(hinban,color,size):
    if len(color)==0 and len(size)==0:
        item_list=list(Shouhin.objects.filter(shouhin_set=hinban).values().order_by("color","size_num"))
    else:
        if len(color)==0:
            item_list=list(Shouhin.objects.filter(shouhin_set=hinban,size__in=size).values().order_by("color","size_num"))
        elif len(size)==0:
            item_list=list(Shouhin.objects.filter(shouhin_set=hinban,color__in=color).values().order_by("color","size_num"))
        else:
            item_list=list(Shouhin.objects.filter(shouhin_set=hinban,color__in=color,size__in=size).values().order_by("color","size_num"))

    return item_list


# 編集_リストクリック
def henshu_list_click(request):
    hontai_num=request.POST.get("hontai_num")
    item=Shouhin.objects.filter(hontai_num=hontai_num).values()[0]    
    d={"item":item}
    return JsonResponse(d)


# 編集_登録/更新
def henshu_up(request):
    dic=request.POST.get("dic")
    dic=json.loads(dic)
    dic["shouhin_set"]=dic["shouhin_num"] + "　" + dic["shouhin_name"]
    dic["size"]=Size.objects.get(size_num=dic["size_num"]).size
    kubun=0
    if dic["hontai_num"]=="":
        dic["hontai_num"]=Shouhin.objects.all().aggregate(Max("hontai_num"))["hontai_num__max"] + 1
        kubun=1

    Shouhin.objects.update_or_create(hontai_num=dic["hontai_num"],defaults=dic)
    d={"kubun":kubun}
    return JsonResponse(d)


# 編集_削除
def henshu_del(request):
    hontai_num=request.POST.get("hontai_num")
    Shouhin.objects.get(hontai_num=hontai_num).delete()
    d={}
    return JsonResponse(d)


# 商品テーブル_download
def henshu_excel_download(request):
    ins=Shouhin.objects.all()
    df=read_frame(ins)

    # Excelファイルをメモリ上に作成
    buffer = BytesIO()
    with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='商品一覧')

    buffer.seek(0)

    # HTTPレスポンスとしてExcelファイルを返す
    response = HttpResponse(
        buffer,
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    response['Content-Disposition'] = 'attachment; filename="products.xlsx"'
    return response


# サイズ画面
@login_required
def size_index(request):
    sizes=Size.objects.all().order_by("size_num")
    request.session["zaiko"]["now_page"]="サイズ"
    return render(request,"zaiko2/size.html",{"sizes":sizes})


# サイズ番号（順番）
def size_num_func(request):
    size_list=request.POST.get("size_list")
    size_list=json.loads(size_list)
    li=[]
    for key,value in size_list.items():
        li.append(value)
    # サイズ一覧
    for size in li:
        ins=Size.objects.get(size=size)
        if ins.size_num != li.index(size)+1:
            ins.size_num=li.index(size)+1
            ins.save()
    #商品一覧
    for size in li:
        ins=Shouhin.objects.filter(size=size)
        if ins.count() != 0:
            ins2=ins[0]
            if ins2.size_num != li.index(size)+1:
                for ins2 in ins:
                    ins2.size_num=li.index(size)+1
                    ins2.save()
    d={"":""}
    return JsonResponse(d)


# サイズ追加
def size_new(request):
    size_new=request.POST.get("size_new")
    Size.objects.create(size_num=0, size=size_new)
    d={"":""}
    return JsonResponse(d)


# サイズ名称
def size_name(request):
    old_n=request.POST.get("size_name1")
    new_n=request.POST.get("size_name2")
    # サイズ一覧
    ins=Size.objects.get(size=old_n)
    ins.size=new_n
    ins.save()
    #商品一覧
    ins=Shouhin.objects.filter(size=old_n)
    if ins.count() != 0:
        for ins2 in ins:
            ins2.size=new_n
            ins2.save()
    d={"":""}
    return JsonResponse(d)


# サイズ削除
def size_del(request):
    size_name=request.POST.get("size_name")
    Size.objects.get(size=size_name).delete()
    # サイズ一覧
    ins=Size.objects.all()
    for i,h in enumerate(ins):
        h.size_num=i+1
        h.save()
    #商品一覧
    ins=Shouhin.objects.all()
    for i in ins:
        i.size_num=Size.objects.get(size=i.size).size_num
        i.save()
    d={"":""}
    return JsonResponse(d)


# 同サイズ使用商品
def size_same(request):
    size_name=request.POST.get("size_name")
    size_same_list=list(Shouhin.objects.filter(size=size_name).values())
    d={"size_same_list":size_same_list}
    return JsonResponse(d)


# 入庫画面
@login_required
def nyuuko_index(request):
    ses_item_list=request.session["zaiko"]["items2"]
    order_list=order_item_list(ses_item_list)
    request.session["zaiko"]["now_page"]="入庫"
    return render(request,"zaiko2/nyuuko.html",{"order_list":order_list})


# 入庫用エクセル_download
def excel_download(request):
    ins=Shouhin.objects.all()
    df=read_frame(ins)
    df=df[["hontai_num","place","shouhin_num","shouhin_name","color","size"]]
    df["stocking"]=0

    # Excelファイルをメモリ上に作成
    buffer = BytesIO()
    with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='入庫専用')

    buffer.seek(0)

    # HTTPレスポンスとしてExcelファイルを返す
    response = HttpResponse(
        buffer,
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    response['Content-Disposition'] = 'attachment; filename="stocking.xlsx"'
    return response


# 入庫用エクセル_import
def excel_import(request):
    if request.method == 'POST' and request.FILES.get('excel_file'):
        excel_file = request.FILES['excel_file']
        wb = openpyxl.load_workbook(excel_file)
        sheet = wb.active
        ses_item_list=request.session["zaiko"]["items2"]

        # 2行目からデータを読み込む（1行目はヘッダー）
        for row in sheet.iter_rows(min_row=2, values_only=True):
            if row[6]>0:
                ses_item_list.append(str(row[0]) + "_" + str(row[6]))
        request.session["zaiko"]["items2"]=ses_item_list
            
    return redirect("zaiko2:nyuuko_index")


# 入庫処理
def nyuuko_send(request):
    tantou=request.POST.get("tantou")
    ses_item_list=request.session["zaiko"]["items2"]
    if len(ses_item_list)==0:
        ans="no"
    else:
        ans="yes"
        try:
            irai_num=Irai_list.objects.all().aggregate(Max("irai_num"))["irai_num__max"] + 1
        except:
            irai_num=1
        
        ####### Irai_list #######
        Irai_list.objects.create(
            irai_num=irai_num,
            shozoku="物流センター",
            tantou=tantou,
            irai_type=3,
            irai_status=5,
        )

        ####### 商品 #######
        for i in ses_item_list:
            hontai,kazu=map(int,i.split("_"))
            ins=Shouhin.objects.get(hontai_num=hontai)

            # Irai_detail
            Irai_detail.objects.create(
                irai_num=irai_num,
                hontai_num=ins.hontai_num,
                place=ins.place,
                shouhin_num=ins.shouhin_num,
                shouhin_name=ins.shouhin_name,
                color=ins.color,
                size=ins.size,
                size_num=ins.size_num,
                tana=ins.tana,
                cost_price=ins.cost_price,
                bikou=ins.bikou,
                attention=ins.attention,
                jan_code=ins.jan_code,
                kazu=kazu,
            )
            # Shouhin
            ins.available += kazu
            ins.stock += kazu
            ins.save()
        request.session["zaiko"]["items2"]=[]

    d={"ans":ans}
    return JsonResponse(d)


# VBA_依頼情報取得POST
@csrf_exempt
def vba_irai_list(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body.decode("utf-8"))
            hassou_type = data.get("hassou_type")
            place = data.get("place")
            
            if hassou_type=="当日":
                ins_lis=Irai_list.objects.filter(irai_status=0,hassou_type=3,place=place)
            elif hassou_type=="全部":
                ins_lis=Irai_list.objects.filter(irai_status=0,place=place)

            # 在庫関連
            irai_num_list=list(ins_lis.values_list("irai_num",flat=True))

new_logi/zaiko2/templates/zaiko2/size.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="icon" href="{% static 'tora.gif' %}">
    <title>物流在庫表（サイズ編集）</title>
</head>
<body>
    <div class="mt-3 mb-5">

        <div style="margin: 0 auto; width: 1100px;">

        <!-- メニュー -->
        {% include "zaiko/menu.html" %}
        <hr>

        <!-- サイズ編集 -->
        <div class="flex mt-5">
            <div style="width: 180px;">
                <div class="inlineframe3" style="height: 500px;">
                    <ol class="drag-list">
                        {% for i in sizes %}
                            {% if i.size_num == 0 %}
                            <li id="{{i.size}}" name="size_list" draggable="true" style="background-color: aqua;">{{i.size}}</li>
                            {% else %}
                            <li id="{{i.size}}" name="size_list" draggable="true">{{i.size}}</li>
                            {% endif %}
                        {% endfor %}
                        <li style="border:0;list-style-type:none;">&nbsp;</li>
                    </ol>
                </div>
                <div class="mt-3" style="text-align: right;">
                    <button type="button" class="btn btn-secondary" id="btn_size_num">順番決定</button>
                </div>
            </div>

            <div style="margin-left: 70px;">
                <div>■ 新サイズ登録</div>
                <div class="mt-3">
                    <div class="flex2">
                        <div>新規：</div>
                        <div style="width: 120px;"><input class="form-control" type="text" id="size_new"></div>
                    </div>
                    <div class="mt-3" style="text-align: right;">
                        <button type="button" class="btn btn-secondary" id="btn_size_new">登録</button>
                    </div>
                </div>
                <hr>
                <div>■ サイズ名変更</div>
                <div class="mt-3">
                    <div class="flex2">
                        <div>現在：</div>
                        <div style="width: 120px;"><input class="form-control" type="text" id="size_name1" readonly></div>
                    </div>
                    <div class="flex2 mt-1">
                        <div>変更：</div>
                        <div style="width: 120px;"><input class="form-control" type="text" id="size_name2"></div>
                    </div>
                    <div class="mt-3" style="text-align: right;">
                        <button type="button" class="btn btn-secondary" id="btn_size_name">変更</button>
                    </div>
                </div>
                <hr>
                <div>■ サイズ削除</div>
                <div class="mt-3">
                    <div class="flex2">
                        <div>削除：</div>
                        <div style="width: 120px;"><input class="form-control" type="text" id="size_del" readonly></div>
                    </div>
                    <div class="mt-3" style="text-align: right;">
                        <button type="button" class="btn btn-outline-danger" id="btn_size_del">削除</button>
                    </div>
                </div>
            </div>

            <div style="margin-left: 70px;">
                <div>【 同じサイズが登録されている商品 】</div>
                <div id="sample_list_count" style="display: none;"></div>
                <div class="inlineframe mt-2" id="sample_list" style="height: 500px; width: 600px;"></div>
            </div>
        </div>

    </div>



    <script>

        // Ajax設定
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i <cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
  
        var csrftoken = getCookie('csrftoken');
  
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
  
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
  

        // サイズ番号決定（順位変更）
        $('#btn_size_num').on('click', function() {
            document.getElementById("btn_size_num").disabled=true;
            var sizes=document.getElementsByName("size_list");
            var size_list={};
            for (var i=0; i<sizes.length; i++){
                size_list[i]=sizes[i].id
            };
            size_list=JSON.stringify(size_list);
            $.ajax({
                'url': '{% url "zaiko2:size_num_func" %}',
                'type': 'POST',
                'data': {'size_list':size_list},
                'dataType': 'json'
            })
            .done(function(response){
                window.location.reload();
                window.alert("サイズ順を変更しました！");
            });            
        });


        // サイズ名称取得
        var sizes=document.getElementsByName("size_list");
        for (var i=0; i<sizes.length; i++){
            sizes[i].addEventListener("click",function(){
                document.getElementById("size_name1").value=this.innerText;
                document.getElementById("size_del").value=this.innerText;
                $.ajax({
                    'url': '{% url "zaiko2:size_same" %}',
                    'type': 'POST',
                    'data': {'size_name':this.innerText},
                    'dataType': 'json'
                })
                .done(function(response){
                    res=response.size_same_list;
                    str="";
                    for (var i of res){
                        str=str + "<div class='flex2 main_size'>" + 
                            "<div style='width:90px;'>" + i.place + "</div>" + 
                            "<div style='width:80px; word-wrap: break-word; padding-right:15px;'>" + i.shouhin_num + "</div>" + 
                            "<div style='width:210px; padding-right:15px;'>" + i.shouhin_name + "</div>" + 
                            "<div style='width:130px; padding-right:15px;'>" + i.color + "</div>" + 
                            "<div>" + i.size + "</div>" + 
                            "</div>";
                    };
                    document.getElementById("sample_list").innerHTML=str;
                    document.getElementById("sample_list_count").innerText=res.length;
                });
            },false)
        };
 

        // 新規サイズ
        $('#btn_size_new').on('click', function() {
            var size_new=document.getElementById("size_new").value;
            if (size_new == ""){
                window.alert("新規サイズ名を入力してください！");
                return
            } else {
                $.ajax({
                    'url': '{% url "zaiko2:size_new" %}',
                    'type': 'POST',
                    'data': {'size_new':size_new},
                    'dataType': 'json'
                })
                .done(function(response){
                    window.location.reload();
                    window.alert("新規サイズを追加しました！\n\n続けて、順番を決定してください。");
                });
            };
        });


        // サイズ名称変更
        $('#btn_size_name').on('click', function() {
            var size_name1=document.getElementById("size_name1").value;
            var size_name2=document.getElementById("size_name2").value;
            if (size_name1 == ""){
                window.alert("変更するサイズを選択してください！");
                return
            } else if (size_name2 == ""){
                window.alert("変更後のサイズ名を入力してください！");
                return
            };
            if (document.getElementById("sample_list_count").innerText > 0){
                var ans =confirm("同じサイズ名を使用している商品が存在します。\n\n本当にサイズ名を変更しますか？");
                if (ans == false){
                    return
                };
            };
            document.getElementById("btn_size_name").disabled=true;
            $.ajax({
                'url': '{% url "zaiko2:size_name" %}',
                'type': 'POST',
                'data': {'size_name1':size_name1,'size_name2':size_name2},
                'dataType': 'json'
            })
            .done(function(response){
                window.location.reload();
                window.alert("サイズ名称を変更しました！");
            });
        });


        // サイズ削除
        $('#btn_size_del').on('click', function() {
            if (document.getElementById("sample_list_count").innerText > 0){
                window.alert("同じサイズ名を使用している商品が存在するため削除できません。\n\n先に該当商品のサイズを変更してください。");
                return
            };
            document.getElementById("btn_size_del").disabled=true;
            $.ajax({
                'url': '{% url "zaiko2:size_del" %}',
                'type': 'POST',
                'data': {'size_name':document.getElementById("size_del").value},
                'dataType': 'json'
            })
            .done(function(response){
                window.location.reload();
                window.alert("削除しました！");
            });
        });


        // リストの並び替え
        document.querySelectorAll('.drag-list li').forEach (elm => {
            elm.ondragstart = function () {
                event.dataTransfer.setData('text/plain', event.target.id);
            };
            elm.ondragover = function () {
                event.preventDefault();
                this.style.borderTop = '2px solid blue';
            };
            elm.ondragleave = function () {
                this.style.borderTop = '';
            };
            elm.ondrop = function () {
                event.preventDefault();
                let id = event.dataTransfer.getData('text/plain');
                let elm_drag = document.getElementById(id);
                this.parentNode.insertBefore(elm_drag, this);
                this.style.borderTop = '';
            };
        });

    </script>
</body>
</html>