new_logi/new_logi/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("zaiko.urls")),
    path('zaiko2/',include("zaiko2.urls")),
]

new_logi/zaiko/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import index,check_0,hinban_enter,hinban_click,color_size_click,place_click,item_add,item_del,order_item_list,order_csv_check,csv_item_add, \
                    zaiko_last_check,ajax_regular_day,irai_send_all,rireki_index,rireki_search,rireki_detail,irai_change_today,irai_cancel, \
                    page_first,page_prev,page_next,page_last,download_excel_1, \
                    irai_reset,irai_keep_hassou,csv_imp,csv_imp_page,free


app_name="zaiko"
urlpatterns = [
    path('', index, name="index"),
    path('login/', auth_views.LoginView.as_view(template_name='zaiko/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('check_0/', check_0, name="check_0"),
    path('hinban_enter/', hinban_enter, name="hinban_enter"),
    path('hinban_click/', hinban_click, name="hinban_click"),
    path('color_size_click/', color_size_click, name="color_size_click"),
    path('place_click/', place_click, name="place_click"),
    path('item_add/', item_add, name="item_add"),
    path('item_del/', item_del, name="item_del"),
    path('order_item_list/', order_item_list, name="order_item_list"),
    path('order_csv_check/', order_csv_check, name="order_csv_check"),
    path('csv_item_add/', csv_item_add, name="csv_item_add"),
    path('zaiko_last_check/', zaiko_last_check, name="zaiko_last_check"),
    path('ajax_regular_day/', ajax_regular_day, name="ajax_regular_day"),
    path('irai_send_all/', irai_send_all, name="irai_send_all"),
    path('rireki_index/', rireki_index, name="rireki_index"),
    path('rireki_search/', rireki_search, name="rireki_search"),
    path('rireki_detail/<int:pk>', rireki_detail, name="rireki_detail"),
    path('irai_change_today/', irai_change_today, name="irai_change_today"),
    path('irai_cancel/', irai_cancel, name="irai_cancel"),
    path('irai_reset/', irai_reset, name="irai_reset"),
    path('irai_keep_hassou/', irai_keep_hassou, name="irai_keep_hassou"),
    path('page_first/', page_first, name="page_first"),
    path('page_prev/', page_prev, name="page_prev"),
    path('page_next/', page_next, name="page_next"),
    path('page_last/', page_last, name="page_last"),

    path('download_excel_1/', download_excel_1, name="download_excel_1"),
    path('csv_imp/', csv_imp, name="csv_imp"),
    path('csv_imp_page/', csv_imp_page, name="csv_imp_page"),
    path('free/', free, name="free"),
]

new_logi/zaiko2/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import henshu_index,henshu_hinban_enter,henshu_hinban_click,henshu_color_size_click,henshu_list_click,henshu_up,henshu_del,henshu_excel_download, \
                    size_index,size_num_func,size_new,size_name,size_del,size_same,nyuuko_index,excel_download,excel_import,nyuuko_send, \
                    vba_irai_list,vba_hassou_data,vba_zaiko_list


app_name="zaiko2"
urlpatterns = [
    path('henshu_index', henshu_index, name="henshu_index"),
    path('henshu_hinban_enter', henshu_hinban_enter, name="henshu_hinban_enter"),
    path('henshu_hinban_click', henshu_hinban_click, name="henshu_hinban_click"),
    path('henshu_color_size_click', henshu_color_size_click, name="henshu_color_size_click"),
    path('henshu_list_click', henshu_list_click, name="henshu_list_click"),
    path('henshu_up', henshu_up, name="henshu_up"),
    path('henshu_del', henshu_del, name="henshu_del"),
    path('henshu_excel_download', henshu_excel_download, name="henshu_excel_download"),
    path('size_index', size_index, name="size_index"),
    path('size_num_func', size_num_func, name="size_num_func"),
    path('size_new', size_new, name="size_new"),
    path('size_name', size_name, name="size_name"),
    path('size_del', size_del, name="size_del"),
    path('size_same', size_same, name="size_same"),
    path('nyuuko_index', nyuuko_index, name="nyuuko_index"),
    path('excel_download', excel_download, name="excel_download"),
    path('excel_import', excel_import, name="excel_import"),
    path('nyuuko_send', nyuuko_send, name="nyuuko_send"),
    path('vba_irai_list', vba_irai_list, name="vba_irai_list"),
    path('vba_hassou_data', vba_hassou_data, name="vba_hassou_data"),
    path('vba_zaiko_list', vba_zaiko_list, name="vba_zaiko_list"),
]

new_logi/zaiko/views.py
from django.shortcuts import render,redirect
from .models import Shouhin,Place,Shozoku,Size,Irai_list,Irai_detail
from django.contrib.auth.decorators import login_required
import io
import csv
import json
from django.http import JsonResponse
from datetime import datetime,timedelta,time
import os
from django.http import FileResponse
from django.conf import settings
import jpholiday
from django.db.models import Max
from django.utils import timezone


# 出荷作業依頼書_ダウンロード
def download_excel_1(request):
    file_path = os.path.join(settings.MEDIA_ROOT, 'excel', '★出荷作業依頼書（原紙）.xlsx')
    os.path.exists(file_path)
    response = FileResponse(open(file_path, 'rb'), as_attachment=True, filename='★出荷作業依頼書（原紙）.xlsx')
    response['Content-Type'] = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    return response


# 在庫依頼_index
@login_required
def index(request):
    if "zaiko" not in request.session:
        request.session["zaiko"]={}
    if "place" not in request.session["zaiko"]:
        request.session["zaiko"]["place"]="物流センター"
    if "items" not in request.session["zaiko"]:
        request.session["zaiko"]["items"]=[]
    if "check_0" not in request.session["zaiko"]:
        request.session["zaiko"]["check_0"]="0"
    if "page_num" not in request.session["zaiko"]:
        request.session["zaiko"]["page_num"]=1
    if "all_page_num" not in request.session["zaiko"]:
        request.session["zaiko"]["all_page_num"]=""
    if "place2" not in request.session["zaiko"]:
        request.session["zaiko"]["place2"]="物流センター"
    if "items2" not in request.session["zaiko"]:
        request.session["zaiko"]["items2"]=[]
    if "rireki_search" not in request.session["zaiko"]:
        request.session["zaiko"]["rireki_search"]={}
    if "now_page" not in request.session["zaiko"]:
        request.session["zaiko"]["now_page"]="在庫"
    

    # キープ解除
    ins=Irai_list.objects.filter(irai_status=1)
    for i in ins:
        if timezone.now() - i.irai_day >= timedelta(days=21):
            i.irai_status=4
            i.cancel_day=datetime.now().strftime("%Y年%m月%d日 %H:%M")
            i.save()
            ins_det=Irai_detail.objects.filter(irai_num=i.irai_num,place=i.place)
            for h in ins_det:
                ins_sho=Shouhin.objects.get(hontai_num=h.hontai_num)
                ins_sho.keep -= h.kazu
                ins_sho.available += h.kazu
                ins_sho.save()

    # 依頼商品一覧
    shozoku_list=Shozoku.objects.all()
    ses_item_list=request.session["zaiko"]["items"]
    order_list=order_item_list(ses_item_list)
    alert=0
    for i in order_list:
        if i["zaiko"]=="ng":
            alert += 1

    # 発送日
    # today=datetime(2025,11,5,9,0,0)
    today=datetime.today()
    regular_day,regular_att=get_regular_day(today)
    hurry_day=get_hurry_day(today)
    hurry_show=True
    if regular_day < hurry_day:
        hurry_show=False

    request.session["zaiko"]["now_page"]="在庫"
    params={
        "shozoku_list":shozoku_list,
        "order_list":order_list,
        "alert":alert,
        "regular":get_day_show(regular_day),
        "regular_day":str(regular_day),
        "regular_att":regular_att,
        "hurry":get_day_show(hurry_day),
        "hurry_day":str(hurry_day),
        "hurry_show":hurry_show,
        "check_0":request.session["zaiko"]["check_0"],
    }
    return render(request,"zaiko/index.html",params)


# FUNC 通常便計算
def get_regular_day(today):
    if today.weekday() in [0,2,4] and jpholiday.is_holiday(today)==False and today.time()<time(10,0,0):
        regular_day=today
        regular_attention="yes"
    else:
        target_day=today + timedelta(days=1)
        while True:
            if target_day.weekday() in [0,2,4] and jpholiday.is_holiday(target_day)==False:
                regular_day=target_day
                regular_attention="no"
                break
            else:
                target_day += timedelta(days=1)
    return (regular_day.date(),regular_attention)


# FUNC お急ぎ便計算
def get_hurry_day(today):
    target_day=today + timedelta(days=1)
    while True:
        if target_day.weekday() not in [5,6] and jpholiday.is_holiday(target_day)==False:
            hurry_day=target_day
            break
        else:
            target_day += timedelta(days=1)
    return hurry_day.date()


# FUNC 日付（表示用）
def get_day_show(day):
    week=["月", "火", "水", "木", "金", "土", "日"]
    day=f"{day.month}月{day.day}日（{week[day.weekday()]}）"
    return day


# ajax_通常便計算
def ajax_regular_day(request):
    today=datetime.today()
    regular_day,regular_att=get_regular_day(today)
    d={"regular":get_day_show(regular_day),"regular_day":regular_day}
    return JsonResponse(d)


# モーダル_発注可能数
def check_0(request):
    check_0=request.POST.get("check_0")
    request.session["zaiko"]["check_0"]=check_0
    d={}
    return JsonResponse(d)


# モーダル_品番検索に入力
def hinban_enter(request):
    hinban_enter=request.POST.get("hinban_enter")
    modal_type=request.POST.get("modal_type")
    check_0_ses=request.session["zaiko"]["check_0"]
    if modal_type=="zaiko" and check_0_ses=="1":
        hinban_list=list(Shouhin.objects.filter(shouhin_set__icontains=hinban_enter,available__gt=0).values_list("shouhin_set",flat=True).order_by("shouhin_set").distinct())
    else:
        hinban_list=list(Shouhin.objects.filter(shouhin_set__icontains=hinban_enter).values_list("shouhin_set",flat=True).order_by("shouhin_set").distinct())                         
    d={"hinban_list":hinban_list}
    return JsonResponse(d)


# モーダル_品番リストをクリック
def hinban_click(request):
    hinban=request.POST.get("hinban")
    modal_type=request.POST.get("modal_type")
    check_0_ses=request.session["zaiko"]["check_0"]
    place_ok=list(Place.objects.filter(show=1))

    if modal_type=="zaiko" and check_0_ses=="1":
        color_list=list(Shouhin.objects.filter(shouhin_set=hinban,available__gt=0).values_list("color",flat=True).order_by("color").distinct())
        size_list=list(Shouhin.objects.filter(shouhin_set=hinban,available__gt=0).values_list("size",flat=True).order_by("size_num").distinct())
        place_list=list(Shouhin.objects.filter(shouhin_set=hinban,place__in=place_ok,available__gt=0).values_list("place",flat=True).distinct())
    else:
        color_list=list(Shouhin.objects.filter(shouhin_set=hinban).values_list("color",flat=True).order_by("color").distinct())
        size_list=list(Shouhin.objects.filter(shouhin_set=hinban).values_list("size",flat=True).order_by("size_num").distinct())
        place_list=list(Shouhin.objects.filter(shouhin_set=hinban,place__in=place_ok).values_list("place",flat=True).distinct())

    place_dic={}
    for i in place_list:
        place_dic[i]=Place.objects.get(place=i).id
    place_list=sorted(place_dic, key=place_dic.get)

    place="物流センター"
    request.session["zaiko"]["place"]="物流センター"
    request.session["zaiko"]["place2"]="物流センター"
    ses_item_list=request.session["zaiko"]["items"]

    d={"color_list":color_list,
       "size_list":size_list,
       "item_list":item_list(hinban,[],[],place,modal_type,check_0_ses),
       "place_list":place_list,
       "place":place,
       "ses_list":ses_list(ses_item_list)
       }
    return JsonResponse(d)


# モーダル_カラー、サイズをクリック
def color_size_click(request):
    hinban=request.POST.get("hinban")
    color=request.POST.get("color")
    color=json.loads(color)
    size=request.POST.get("size")
    size=json.loads(size)
    modal_type=request.POST.get("modal_type")
    check_0_ses=request.session["zaiko"]["check_0"]
    if modal_type=="zaiko":
        place=request.session["zaiko"]["place"]
        ses_item_list=request.session["zaiko"]["items"]
    else:
        place=request.session["zaiko"]["place2"]
        ses_item_list=request.session["zaiko"]["items2"]
    d={
        "item_list":item_list(hinban,color,size,place,modal_type,check_0_ses),
        "ses_list":ses_list(ses_item_list)
        }
    return JsonResponse(d)


# FUNC 商品リスト取得
def item_list(hinban,color,size,place,modal_type,check_0_ses):
    if modal_type=="zaiko" and check_0_ses=="1":
        if len(color)==0 and len(size)==0:
            item_list=list(Shouhin.objects.filter(shouhin_set=hinban,place=place,available__gt=0).values().order_by("color","size_num"))
        else:
            if len(color)==0:
                item_list=list(Shouhin.objects.filter(shouhin_set=hinban,size__in=size,place=place,available__gt=0).values().order_by("color","size_num"))
            elif len(size)==0:
                item_list=list(Shouhin.objects.filter(shouhin_set=hinban,color__in=color,place=place,available__gt=0).values().order_by("color","size_num"))
            else:
                item_list=list(Shouhin.objects.filter(shouhin_set=hinban,color__in=color,size__in=size,place=place,available__gt=0).values().order_by("color","size_num"))
    else:
        if len(color)==0 and len(size)==0:
            item_list=list(Shouhin.objects.filter(shouhin_set=hinban,place=place).values().order_by("color","size_num"))
        else:
            if len(color)==0:
                item_list=list(Shouhin.objects.filter(shouhin_set=hinban,size__in=size,place=place).values().order_by("color","size_num"))
            elif len(size)==0:
                item_list=list(Shouhin.objects.filter(shouhin_set=hinban,color__in=color,place=place).values().order_by("color","size_num"))
            else:
                item_list=list(Shouhin.objects.filter(shouhin_set=hinban,color__in=color,size__in=size,place=place).values().order_by("color","size_num"))

    return item_list


# FUNC 追加済み商品取得
def ses_list(ses_item_list):
    ses_list=[]
    for i in ses_item_list:
        ses_list.append(i.split("_")[0])
    return ses_list


# モーダル_拠点選択
def place_click(request):
    hinban=request.POST.get("hinban")
    color=request.POST.get("color")
    color=json.loads(color)
    size=request.POST.get("size")
    size=json.loads(size)
    place=request.POST.get("place")
    modal_type=request.POST.get("modal_type")

new_logi/zaiko/templates/zaiko/csv_imp.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DB取込</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    <div style="width: 500px;">
        <form action="{% url 'zaiko:csv_imp' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            <label for="csv1">在庫リスト：</label>
            <input class="form-control" type="file" name="csv1" id="csv1">
            <br>
            <input type="submit" name="btn_upload" value="取込">
            <span style="color: red;">　{{message}}</span>
        </form>
    </div>

</body>
</html>

new_logi/zaiko/templates/zaiko/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <link rel="icon" href="{% static 'tora.gif' %}">
    <title>物流在庫表（ログイン）</title>
</head>
<body>
    <div class="login flex">
        <form class="form-signin" method="POST">{% csrf_token %}
            <div>
                <div style="margin-top: 10px; text-align: center;"><img src="{% static 'logo.png' %}"></div>
            </div>
            <div class="login_title flex2" style="margin-top: 25px;">
                <div style="margin-left: 20px;"><img src="{% static 'car_kei-van.gif' %}"></div>
                <div style="margin-left: 20px;">物流在庫表</div>
            </div>
            <div style="margin-top: 20px;">
                <table style="margin-left: auto; margin-right: auto;">
                    <tr>
                        {% if form.errors %}
                            <p style="color: red;">ユーザー名かパスワードが間違っています。</p>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>ログインID：</td>
                        <td><input class="form-control" type="text" name="username" style="width: 150px;"></td>
                    </tr>
                    <tr>
                        <td style="padding-top: 10px; text-align: right;">パスワード：</td>
                        <td style="padding-top: 10px;"><input class="form-control" type="password" name="password" style="width: 150px;"></td>
                    </tr>
                    <tr>
                        <td colspan="2" style="text-align: center; padding-top: 10px;">
                            <button type="submit" class="btn btn-success mb-2" style="width: 100%;">ログイン</button>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>

</body>
</html>

new_logi/zaiko/templates/zaiko/menu.html
{% load static %}
<!-- メニュー -->
<div class="flex2">

    <!-- 依頼側 -->
    <div>
        <a href="https://www.p1-intl.com/" target="_blank"><img src="{% static 'logo.png' %}"></a>
    </div>
    <div style="margin-left: 30px;">
        <a href="{% url 'zaiko:index' %}">
            {% if request.session.zaiko.now_page == "在庫" %}
            <button type="button" class="btn btn-dark">
            {% else %}
            <button type="button" class="btn btn-outline-dark">
            {% endif %}
            物流在庫表</button>
        </a>
    </div>
    <div style="margin-left: 30px;">
        <a href="{% url 'zaiko:rireki_index' %}">
            {% if request.session.zaiko.now_page == "一覧" %}
            <button type="button" class="btn btn-dark">
            {% else %}
            <button type="button" class="btn btn-outline-dark">
            {% endif %}
            履歴一覧（修正 / キャンセル）</button>
        </a>
    </div>

    <!-- 管理側 -->
    {% if request.user.username == "p1masao" %}
    <div style="margin-left: 30px;">
        <a href="{% url 'zaiko2:henshu_index' %}">
            {% if request.session.zaiko.now_page == "編集" %}
            <button type="button" class="btn btn-dark">
            {% else %}
            <button type="button" class="btn btn-outline-dark">
            {% endif %}
            商品登録 / 編集</button>
        </a>
    </div>
    <div style="margin-left: 30px;">
        <a href="{% url 'zaiko2:size_index' %}">
            {% if request.session.zaiko.now_page == "サイズ" %}
            <button type="button" class="btn btn-dark">
            {% else %}
            <button type="button" class="btn btn-outline-dark">
            {% endif %}
            サイズ</button>
        </a>
    </div>
    <div style="margin-left: 30px;">
        <a href="{% url 'zaiko2:nyuuko_index' %}">
            {% if request.session.zaiko.now_page == "入庫" %}
            <button type="button" class="btn btn-dark">
            {% else %}
            <button type="button" class="btn btn-outline-dark">
            {% endif %}
            入庫処理</button>
        </a>
    </div>
    <div style="margin-left: 30px;">
        <a href="{% url 'admin:index' %}" target="_blank"><button type="button" class="btn btn-outline-danger">DB</button></a>
    </div>
    {% endif %}
    
</div>